### ISSUE TITLE
recreate folder structure when unpacking

### ISSUE THREAD

**Issue by r-lyeh** [r-lyeh/bundler#1]
@todo

**Comment by snail23** [comment]
Implemented for windows only in https://github.com/snail23/bundler/commit/6d5c2c101f7d998f4c364007948987b2090ed819 if you want to take a look and modify it to be more universal. (Kind of hacked together for my needs)

**Comment by r-lyeh** [comment]
Aha thanks. I dunno why the bug has been never solved so far. I am pretty forgetful sometimes :)
I'd like to replace Sao with Apathy someday (it has a function to fix this, I guess).

**Comment by r-lyeh** [comment]
Btw, since I cannot open issues in starborn and I am curious to know: why did you replace cocoa and collage? found bugs maybe? on the other hand, did you consider kult for entity/component/systems? I'd like someone developing a real game to give it a try :)
Thanks for using so many libs of mine, I will be looking forward what you made of this :)

**Comment by snail23** [comment]
Ah yeah I'm not using the github issue tracker for any of my projects atm, thanks for reminding me. :p

Cocoa was pretty great but there was some kind of bug related to the SHA1 functions which is what I'm using as part of the update system so that's why I replaced that, the library itself is quite good though. 

As for collage, the diff files produced were larger than the original files so I decided to just straight up replace the files with a base91 encoded version of the binaries. (You should get it running on non-binary data like git diffs, I'd totally use it for text files!)

As for kult, I'm actually seriously considering using it or https://github.com/arvidsson/entity and probably https://github.com/jeremyletang/safe_event if I can't find a good event system to go along with it.

You have some great libraries overall, I'm glad I ran into them after the status thread on /r/gamedev! :D

**Comment by r-lyeh** [comment]
Lol @ collage :) 

Hmmm ... I wonder what is the problem with SHA1 actually.
May it be incorrect hashes when a long text/binary stream is processed in pieces?
If you manage to find the problem, drop an issue on the cocoa issue tracker :)

**Comment by snail23** [comment]
Yeah it was definitely related to large strings though it seemed to only crash when reading directly from flow::download(), I have another utility program that precomputes hashes from files and that seemed to work just fine. I'll redownload cocoa and see if I can mess with it a bit.

**Comment by r-lyeh** [comment]
yep thanks for testing :) 
btw, included some of your changes in 7336a67
thanks for fixing this issue :)
i am closing the issue now!
